<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../UseNotch.Application/UseNotch.Application.csproj" />
    <PackageReference Include="Microsoft.Win32.SystemEvents" />
  </ItemGroup>
</Project>
