<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia.Headless.XUnit" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/UseNotch.App/UseNotch.App.csproj" />
  </ItemGroup>
</Project>
